//
//  Workspace.swift
//  ExamplesManifests
//
//  Created by Gihyun on 11/24/24.
//

import ProjectDescription

let workSpace = Workspace(
  name: "ComponentsArchitecture-Example",
  projects: ["Projects/App"],
  generationOptions: .options(
    enableAutomaticXcodeSchemes: false,
    autogeneratedWorkspaceSchemes: .disabled
  )
)
